-- 코드를 입력하세요
-- 1. 보호소에서 나간 동물 중 중성화된 동물 ID를 출력
-- 2. 1.의 ID와 일치하는 보호소 들어온 동물 중 중성화되지 않은 동물 목록 출력
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
INNER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE (AO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%') AND
(AI.SEX_UPON_INTAKE LIKE 'Intact%')
ORDER BY AI.ANIMAL_ID ASC;