-- 코드를 입력하세요
SELECT
    U.USER_ID,
    U.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U
INNER JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;

-- '거래 완료 된' 중고 거래의 '총 금액'이 '70만 원' '이상'인 '회원'의 회원ID, 닉네임, 총거래금액을 총거래금액 기준 오름차순 조회