-- 코드를 입력하세요
-- 2022-10-16을 범위 내에 담고 있는 임시 테이블 또는 셀렉트문을 만들어서 풀기
WITH RENTAL AS (
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)
SELECT DISTINCT(H.CAR_ID), IFNULL(R.AVAILABILITY, '대여 가능')
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN RENTAL R ON H.CAR_ID = R.CAR_ID
ORDER BY H.CAR_ID DESC;