-- 코드를 입력하세요
# CAR_RENTAL_COMPANY_CAR 테이블과 
# CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 
# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 
# 대여 기록 별로 총 대여 금액(컬럼명: FEE)을 구하여 
# 대여 기록 ID, 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 
# 결과는 대여 금액, 대여 기록 ID를 기준으로 내림차순 정렬해주세요.
SELECT
    RH.HISTORY_ID,
    CASE
        WHEN RH.RENTAL_PERIOD < 7 THEN ROUND(C.DAILY_FEE * RH.RENTAL_PERIOD, 0)
        ELSE ROUND((C.DAILY_FEE * RH.RENTAL_PERIOD) * (1 - DP.DISCOUNT_RATE / 100), 0)
    END AS FEE
FROM (
    SELECT 
        HISTORY_ID, 
        CAR_ID, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_PERIOD,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS RH
INNER JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_TYPE = '트럭' AND RH.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON DP.CAR_TYPE = '트럭' AND RH.DURATION_TYPE = DP.DURATION_TYPE
GROUP BY RH.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;