-- 코드를 입력하세요
SELECT ONLINE_SALE.USER_ID, ONLINE_SALE.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS SALE_COUNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING SALE_COUNT >= 2
    ORDER BY USER_ID ASC, PRODUCT_ID DESC
) AS ONLINE_SALE;