-- 코드를 입력하세요
SELECT M.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN (
    SELECT RR.MEMBER_ID, MP.MEMBER_NAME
    FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) M ON RR.MEMBER_ID = M.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, REVIEW_TEXT ASC;