-- 코드를 입력하세요
-- 1. 2022 08 ~ 10 기준 총 대여횟수 5회 이상인 자동차 CAR_ID를 검색
-- 2. 그 자동차들의 2022 08 ~ 10 기간 동안 대여한 횟수를 월별로 검색
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;